version: '3.8'
services:
  app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: api
      volumes:
        - .:/app
      ports:
        - '8080:8080'
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
        - API_KEY=${API_KEY}
        - PORT=${PORT}
        - HOST=${HOST}
      networks:
      - desafio-db

  db:
    image: mysql/mysql-server:8.0.32-1.2.11-server
    container_name: database
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
    volumes:
      - volumes:/var/lib/mysql
      - ./docs/db/mysql/database.sql:/docker-entrypoint-initdb.d/01-database.sql
      - ./docs/db/mysql/data.sql:/docker-entrypoint-initdb.d/02-data.sql
    networks:
      - desafio-db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  volumes:
    driver: local

networks:
  desafio-db:
    driver: bridge